-- Initial backend foundation schema.
-- This SQL mirrors prisma/schema.prisma and is intentionally checked in so the
-- database contract is reviewable before a network-enabled Prisma CLI install.

CREATE TYPE "Role" AS ENUM ('admin', 'supervisor', 'contractor_manager', 'rectifier');
CREATE TYPE "OrganizationType" AS ENUM ('owner', 'supervisor', 'contractor', 'other');
CREATE TYPE "SiteItemType" AS ENUM ('defect', 'punch');
CREATE TYPE "SiteItemStatus" AS ENUM ('pending_approval', 'dispatched', 'rectifying', 'pending_acceptance', 'closed', 'voided');
CREATE TYPE "Severity" AS ENUM ('normal', 'important', 'severe');
CREATE TYPE "PhotoStage" AS ENUM ('discovery', 'rectification', 'review');
CREATE TYPE "WorkflowAction" AS ENUM ('create', 'dispatch', 'assign_rectifier', 'start_rectify', 'submit_review', 'return_rectification', 'close', 'void', 'reopen', 'comment');
CREATE TYPE "NotificationType" AS ENUM ('assigned', 'review_requested', 'due_soon', 'overdue', 'voided', 'reopened');
CREATE TYPE "ExportType" AS ENUM ('excel', 'photo_package', 'pdf');
CREATE TYPE "ExportStatus" AS ENUM ('queued', 'running', 'succeeded', 'failed');

CREATE TABLE "Project" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "code" TEXT UNIQUE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "Section" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id"), "name" TEXT NOT NULL, "code" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, UNIQUE ("projectId", "code"));
CREATE TABLE "Organization" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id"), "name" TEXT NOT NULL, "type" "OrganizationType" NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, UNIQUE ("projectId", "name"));
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id"), "organizationId" TEXT NOT NULL REFERENCES "Organization"("id"), "name" TEXT NOT NULL, "phone" TEXT UNIQUE NOT NULL, "username" TEXT UNIQUE NOT NULL, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "UserSectionScope" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id"), "sectionId" TEXT NOT NULL REFERENCES "Section"("id"), UNIQUE ("userId", "sectionId"));
CREATE TABLE "Area" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id"), "parentId" TEXT REFERENCES "Area"("id"), "name" TEXT NOT NULL, "code" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, UNIQUE ("projectId", "code"));
CREATE TABLE "Discipline" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id"), "name" TEXT NOT NULL, "code" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, UNIQUE ("projectId", "code"));
CREATE TABLE "Drawing" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id"), "areaId" TEXT NOT NULL REFERENCES "Area"("id"), "disciplineId" TEXT REFERENCES "Discipline"("id"), "name" TEXT NOT NULL, "code" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), UNIQUE ("projectId", "code"));
CREATE TABLE "DrawingRevision" ("id" TEXT PRIMARY KEY, "drawingId" TEXT NOT NULL REFERENCES "Drawing"("id"), "revisionNo" TEXT NOT NULL, "fileKey" TEXT NOT NULL, "coverPreviewKey" TEXT NOT NULL, "pageCount" INTEGER NOT NULL, "uploadedBy" TEXT NOT NULL, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "isCurrent" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "DrawingRevisionPage" ("id" TEXT PRIMARY KEY, "drawingRevisionId" TEXT NOT NULL REFERENCES "DrawingRevision"("id"), "pageNumber" INTEGER NOT NULL, "previewKey" TEXT NOT NULL, "width" INTEGER NOT NULL, "height" INTEGER NOT NULL, UNIQUE ("drawingRevisionId", "pageNumber"));
CREATE TABLE "SiteItem" ("id" TEXT PRIMARY KEY, "projectId" TEXT NOT NULL REFERENCES "Project"("id"), "sectionId" TEXT NOT NULL REFERENCES "Section"("id"), "itemNo" TEXT UNIQUE NOT NULL, "type" "SiteItemType" NOT NULL, "status" "SiteItemStatus" NOT NULL, "severity" "Severity" NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "areaId" TEXT NOT NULL REFERENCES "Area"("id"), "disciplineId" TEXT NOT NULL REFERENCES "Discipline"("id"), "locationText" TEXT NOT NULL, "responsibleOrgId" TEXT REFERENCES "Organization"("id"), "responsibleUserId" TEXT REFERENCES "User"("id"), "createdBy" TEXT NOT NULL REFERENCES "User"("id"), "ownerUserId" TEXT NOT NULL REFERENCES "User"("id"), "defaultDueAt" TIMESTAMP NOT NULL, "dueAt" TIMESTAMP NOT NULL, "submittedForReviewAt" TIMESTAMP, "closedAt" TIMESTAMP, "reopenedAt" TIMESTAMP, "voidedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "PhotoAttachment" ("id" TEXT PRIMARY KEY, "siteItemId" TEXT REFERENCES "SiteItem"("id"), "stage" "PhotoStage", "objectKey" TEXT UNIQUE NOT NULL, "thumbnailKey" TEXT NOT NULL, "fileName" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" INTEGER NOT NULL, "uploadedBy" TEXT NOT NULL REFERENCES "User"("id"), "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "sectionSnapshot" TEXT, "areaSnapshot" TEXT, "disciplineSnapshot" TEXT, "responsibleOrgSnapshot" TEXT);
CREATE TABLE "WorkflowLog" ("id" TEXT PRIMARY KEY, "siteItemId" TEXT NOT NULL REFERENCES "SiteItem"("id"), "action" "WorkflowAction" NOT NULL, "fromStatus" "SiteItemStatus", "toStatus" "SiteItemStatus", "comment" TEXT NOT NULL, "actorId" TEXT NOT NULL REFERENCES "User"("id"), "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "Notification" ("id" TEXT PRIMARY KEY, "recipientId" TEXT NOT NULL REFERENCES "User"("id"), "siteItemId" TEXT REFERENCES "SiteItem"("id"), "type" "NotificationType" NOT NULL, "title" TEXT NOT NULL, "content" TEXT NOT NULL, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "ExportJob" ("id" TEXT PRIMARY KEY, "type" "ExportType" NOT NULL, "status" "ExportStatus" NOT NULL, "requestedBy" TEXT NOT NULL REFERENCES "User"("id"), "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY, "actorId" TEXT NOT NULL REFERENCES "User"("id"), "action" TEXT NOT NULL, "resourceType" TEXT NOT NULL, "resourceId" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP NOT NULL DEFAULT now());
CREATE TABLE "IdempotencyRecord" ("id" TEXT PRIMARY KEY, "actorId" TEXT NOT NULL, "method" TEXT NOT NULL, "path" TEXT NOT NULL, "key" TEXT NOT NULL, "requestHash" TEXT NOT NULL, "responseStatus" INTEGER NOT NULL, "responseBody" JSONB NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, UNIQUE ("actorId", "method", "path", "key"));
