#!/usr/bin/env node

import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const defaultProjectRoot = resolve(scriptDir, "../..");

const defaults = {
  appImageTag: "local",
  postgresDb: "site_management",
  postgresUser: "site_user",
  postgresHostPort: "5432",
  apiHostPort: "4000",
  webHostPort: "8080",
  s3Bucket: "site-management",
  minioApiHostPort: "9000",
  minioConsoleHostPort: "9001",
  uploadMaxBytes: "10485760",
  idempotencyTtlHours: "24",
  backupDir: "/var/backups/site-management",
  smokeUsername: "wang.supervisor"
};

function secret(bytes = 32) {
  return randomBytes(bytes).toString("base64url");
}

function usage() {
  return [
    "Usage: npm run prod:init-env -- --host <server-host-or-ip> [options]",
    "",
    "Options:",
    "  --output <path>             Output file, defaults to .env.production",
    "  --force                     Overwrite existing output file",
    "  --api-port <port>           Public API port, defaults to 4000",
    "  --web-port <port>           Public Web port, defaults to 8080",
    "  --api-url <url>             Override PUBLIC_API_BASE_URL",
    "  --web-url <url>             Override PUBLIC_WEB_BASE_URL",
    "  --backup-dir <path>         Backup directory, defaults to /var/backups/site-management",
    "  --smoke-username <name>     Smoke account username",
    "  --smoke-password <value>    Smoke account password; generated if omitted",
    "  --image-tag <tag>           Image tag, defaults to local"
  ].join("\n");
}

function readOption(argv, index) {
  const value = argv[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`Missing value for ${argv[index]}`);
  return value;
}

export function parseArgs(argv) {
  const options = {
    host: "",
    output: ".env.production",
    force: false,
    ...defaults
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--force") {
      options.force = true;
      continue;
    }
    if (arg === "--host") options.host = readOption(argv, index++);
    else if (arg === "--output") options.output = readOption(argv, index++);
    else if (arg === "--api-port") options.apiHostPort = readOption(argv, index++);
    else if (arg === "--web-port") options.webHostPort = readOption(argv, index++);
    else if (arg === "--api-url") options.publicApiBaseUrl = readOption(argv, index++);
    else if (arg === "--web-url") options.publicWebBaseUrl = readOption(argv, index++);
    else if (arg === "--backup-dir") options.backupDir = readOption(argv, index++);
    else if (arg === "--smoke-username") options.smokeUsername = readOption(argv, index++);
    else if (arg === "--smoke-password") options.smokePassword = readOption(argv, index++);
    else if (arg === "--image-tag") options.appImageTag = readOption(argv, index++);
    else if (arg === "--help" || arg === "-h") options.help = true;
    else throw new Error(`Unknown option: ${arg}`);
  }

  return options;
}

function assertHost(host) {
  if (!host) throw new Error("--host is required");
  if (host.includes("://") || host.includes("/") || host.includes("SERVER_HOSTNAME_OR_IP")) {
    throw new Error("--host must be a bare hostname or IP address, without protocol or path");
  }
}

function assertPort(label, port) {
  if (!/^\d+$/.test(String(port))) throw new Error(`${label} must be a numeric port`);
}

export function buildEnv(options) {
  assertHost(options.host);
  assertPort("--api-port", options.apiHostPort);
  assertPort("--web-port", options.webHostPort);

  const publicApiBaseUrl = options.publicApiBaseUrl ?? `http://${options.host}:${options.apiHostPort}`;
  const publicWebBaseUrl = options.publicWebBaseUrl ?? `http://${options.host}:${options.webHostPort}`;

  return [
    "# Generated by scripts/prod/init-env.mjs. Do not commit this file.",
    "",
    `APP_IMAGE_TAG=${options.appImageTag}`,
    "",
    `POSTGRES_DB=${options.postgresDb}`,
    `POSTGRES_USER=${options.postgresUser}`,
    `POSTGRES_PASSWORD=${secret(32)}`,
    `POSTGRES_HOST_PORT=${options.postgresHostPort}`,
    "",
    `API_HOST_PORT=${options.apiHostPort}`,
    `WEB_HOST_PORT=${options.webHostPort}`,
    `PUBLIC_API_BASE_URL=${publicApiBaseUrl}`,
    `PUBLIC_WEB_BASE_URL=${publicWebBaseUrl}`,
    `API_CORS_ORIGIN=${publicWebBaseUrl}`,
    "",
    `S3_BUCKET=${options.s3Bucket}`,
    `S3_ACCESS_KEY=${secret(24)}`,
    `S3_SECRET_KEY=${secret(32)}`,
    `MINIO_API_HOST_PORT=${options.minioApiHostPort}`,
    `MINIO_CONSOLE_HOST_PORT=${options.minioConsoleHostPort}`,
    "",
    `JWT_SECRET=${secret(48)}`,
    `UPLOAD_MAX_BYTES=${options.uploadMaxBytes}`,
    `IDEMPOTENCY_TTL_HOURS=${options.idempotencyTtlHours}`,
    "",
    `BACKUP_DIR=${options.backupDir}`,
    "",
    `SMOKE_USERNAME=${options.smokeUsername}`,
    `SMOKE_PASSWORD=${options.smokePassword ?? secret(24)}`,
    ""
  ].join("\n");
}

export async function run(argv = process.argv.slice(2), runtime = {}) {
  const options = parseArgs(argv);
  const stdout = runtime.stdout ?? process.stdout;
  const cwd = runtime.cwd ?? defaultProjectRoot;

  if (options.help) {
    stdout.write(`${usage()}\n`);
    return { help: true };
  }

  const outputPath = resolve(cwd, options.output);
  if (existsSync(outputPath) && !options.force) {
    throw new Error(`${outputPath} already exists. Re-run with --force to overwrite.`);
  }

  const content = buildEnv(options);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content, { flag: options.force ? "w" : "wx", mode: 0o600 });
  stdout.write(`Created ${outputPath}\n`);
  stdout.write("Next: create the BACKUP_DIR on the server, create/import the smoke user, then run npm run prod:preflight.\n");
  return { outputPath, content };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  run().catch((error) => {
    console.error(`ERROR: ${error instanceof Error ? error.message : String(error)}`);
    console.error("");
    console.error(usage());
    process.exit(1);
  });
}
